[package]
name = "goto"
version = "0.1.0"
authors = ["Michal Franc <lam.michal.franc@gmail.com>"]
edition = "2018"

[dependencies]
quicli = "0.4"
structopt = "0.2"
git2 = "0.8"
failure = "0.1.5"
derive_more = "0.14.0"
